export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h1>This is about page</h1>
    </div>
  );
};

export default AboutPage;
