import { Roboto } from "next/font/google";
import "./globals.css";
import Navber from "@/components/shared/Navber";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "My next js app m-40",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={roboto.className}>
        <Navber />
        {children}
      </body>
    </html>
  );
}
